import { UniversityProfile } from '../types/lifeOs';

/**
 * Illustrative starting list only — acceptance rates and essay requirements
 * shift year to year. Treat every figure here as a rough anchor to verify
 * against the university's current admissions page, not as live or
 * authoritative data.
 */
export const UNIVERSITY_DATASET: UniversityProfile[] = [
  {
    id: 'univ-uw',
    name: 'University of Washington',
    acceptanceRatePct: 48,
    campusSize: 'Large',
    locationVibe: 'Urban',
    strongMajors: ['Economics', 'Public Policy', 'Environmental Science', 'Data Science', 'Biology'],
    essayRequirements: ['Personal statement (Coalition/UW app)', 'Short answer: community & goals'],
  },
  {
    id: 'univ-uc-berkeley',
    name: 'UC Berkeley',
    acceptanceRatePct: 11,
    campusSize: 'Large',
    locationVibe: 'Urban',
    strongMajors: ['Economics', 'Public Policy', 'Environmental Science', 'Political Science', 'Data Science'],
    essayRequirements: ['UC Personal Insight Questions (4 of 8)'],
  },
  {
    id: 'univ-uc-la',
    name: 'UCLA',
    acceptanceRatePct: 9,
    campusSize: 'Large',
    locationVibe: 'Urban',
    strongMajors: ['Economics', 'Political Science', 'Public Affairs', 'Biology'],
    essayRequirements: ['UC Personal Insight Questions (4 of 8)'],
  },
  {
    id: 'univ-uc-davis',
    name: 'UC Davis',
    acceptanceRatePct: 46,
    campusSize: 'Large',
    locationVibe: 'Suburban',
    strongMajors: ['Environmental Science', 'Economics', 'Biology', 'Public Policy'],
    essayRequirements: ['UC Personal Insight Questions (4 of 8)'],
  },
  {
    id: 'univ-uc-santa-barbara',
    name: 'UC Santa Barbara',
    acceptanceRatePct: 26,
    campusSize: 'Large',
    locationVibe: 'Suburban',
    strongMajors: ['Environmental Science', 'Economics', 'Political Science'],
    essayRequirements: ['UC Personal Insight Questions (4 of 8)'],
  },
  {
    id: 'univ-uva',
    name: 'University of Virginia',
    acceptanceRatePct: 19,
    campusSize: 'Large',
    locationVibe: 'Suburban',
    strongMajors: ['Economics', 'Public Policy', 'Political Science', 'Environmental Science'],
    essayRequirements: ['Community essay', 'Why UVA / academic curiosity essay'],
  },
  {
    id: 'univ-unc',
    name: 'UNC Chapel Hill',
    acceptanceRatePct: 17,
    campusSize: 'Large',
    locationVibe: 'Suburban',
    strongMajors: ['Public Policy', 'Economics', 'Environmental Science', 'Biology'],
    essayRequirements: ['Why major essay', 'Short-answer supplement'],
  },
  {
    id: 'univ-umich',
    name: 'University of Michigan',
    acceptanceRatePct: 18,
    campusSize: 'Large',
    locationVibe: 'Suburban',
    strongMajors: ['Public Policy', 'Economics', 'Environmental Science', 'Data Science'],
    essayRequirements: ['Community essay', "'Why Michigan' short answer"],
  },
  {
    id: 'univ-tufts',
    name: 'Tufts University',
    acceptanceRatePct: 11,
    campusSize: 'Medium',
    locationVibe: 'Suburban',
    strongMajors: ['Economics', 'Environmental Science', 'Political Science', 'International Relations'],
    essayRequirements: ['Why Tufts short answer', 'Kaledoscope essay option'],
  },
  {
    id: 'univ-wesleyan',
    name: 'Wesleyan University',
    acceptanceRatePct: 14,
    campusSize: 'Small',
    locationVibe: 'Suburban',
    strongMajors: ['Environmental Science', 'Economics', 'Sociology', 'Public Policy'],
    essayRequirements: ['Why Wesleyan essay'],
  },
  {
    id: 'univ-macalester',
    name: 'Macalester College',
    acceptanceRatePct: 30,
    campusSize: 'Small',
    locationVibe: 'Urban',
    strongMajors: ['Political Science', 'Environmental Studies', 'Economics'],
    essayRequirements: ['Why Macalester essay'],
  },
  {
    id: 'univ-lclark',
    name: 'Lewis & Clark College',
    acceptanceRatePct: 68,
    campusSize: 'Small',
    locationVibe: 'Urban',
    strongMajors: ['Environmental Studies', 'Political Science', 'Biology', 'Economics'],
    essayRequirements: ['Standard Common App essay only'],
  },
  {
    id: 'univ-wsu',
    name: 'Washington State University',
    acceptanceRatePct: 82,
    campusSize: 'Large',
    locationVibe: 'Rural',
    strongMajors: ['Environmental Science', 'Biology', 'Economics'],
    essayRequirements: ['Optional personal statement'],
  },
  {
    id: 'univ-wwu',
    name: 'Western Washington University',
    acceptanceRatePct: 91,
    campusSize: 'Medium',
    locationVibe: 'Urban',
    strongMajors: ['Environmental Science', 'Political Science', 'Economics'],
    essayRequirements: ['Optional personal statement'],
  },
];
